# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 16:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mediafiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=mediafiles.models.get_path)),
                ('path', models.CharField(blank=True, max_length=150, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('song', 'song file'), ('poem', 'poem file'), ('video', 'video file'), ('cover', 'cover photo file')], default='song', max_length=20)),
                ('resource_type', models.IntegerField(choices=[(0, 'Local Resource'), (1, 'Backtory')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
