# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0002_auto_20180221_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
