# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-18 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0003_auto_20180222_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='type',
            field=models.CharField(choices=[('song', 'song file'), ('poem', 'poem file'), ('video', 'video file'), ('cover', 'cover photo file'), ('karaoke', 'Karaoke File')], default='song', max_length=20),
        ),
    ]
