# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-22 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0004_auto_20180618_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asynctask',
            name='type',
            field=models.CharField(choices=[('karaokes', 'Upload Karaokes'), ('reports', 'Generate Reports')], default='karaokes', max_length=128),
        ),
    ]
