# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='new-genre', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Karaoke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SongsOriginalName', max_length=100)),
                ('file', models.FileField(upload_to='KaraokeFiles')),
                ('rate', models.IntegerField(default=0)),
                ('rate_count', models.IntegerField(default=0)),
                ('cover_photo', models.FileField(blank=True, null=True, upload_to='example')),
                ('genre', models.ManyToManyField(to='karaoke.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', help_text='write your text line here', max_length=300)),
                ('start_time', models.IntegerField(default=0, help_text='in milliseconds')),
                ('end_time', models.IntegerField(default=0, help_text='in milliseconds')),
                ('karaoke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karaoke.Karaoke')),
            ],
        ),
    ]
