# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='new-genre', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_type', models.CharField(choices=[('system', 'System ownership'), ('user', 'User ownership')], default='system', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('ownership_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='karaoke.OwnerShip')),
                ('name', models.CharField(default='', help_text='Write songs name', max_length=60)),
                ('subclass_type', models.CharField(choices=[('song', 'song object'), ('poem', 'poem object')], default='song', max_length=20)),
                ('description', models.CharField(default='', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_date'],
            },
            bases=('karaoke.ownership',),
        ),
    ]
