# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Write songs name', max_length=60)),
                ('recorded_file', models.FileField(upload_to='KaraokeFiles')),
                ('like_state', models.BooleanField(default=False)),
                ('genre', models.ManyToManyField(null=True, to='karaoke.Genre')),
                ('karaoke', models.ManyToManyField(to='karaoke.Karaoke')),
            ],
        ),
    ]
