# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-11 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karaoke', '0001_initial'),
        ('analytics', '0002_auto_20171111_1708'),
        ('loginapp', '0001_initial'),
        ('mediafiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='composer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composed', to='loginapp.Artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_song', to='mediafiles.MediaFile'),
        ),
        migrations.AddField(
            model_name='song',
            name='poet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_poems', to='loginapp.Artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='karaoke.Post'),
        ),
        migrations.AddField(
            model_name='song',
            name='related_poem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karaoke.Poem'),
        ),
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='singed', to='loginapp.Artist'),
        ),
        migrations.AddField(
            model_name='post',
            name='cover_photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_cover', to='mediafiles.MediaFile'),
        ),
        migrations.AddField(
            model_name='post',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_posts', through='analytics.Favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karaoke.Genre'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', through='analytics.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(through='analytics.TagPost', to='analytics.Tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poem',
            name='poet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loginapp.Artist'),
        ),
        migrations.AddField(
            model_name='poem',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='karaoke.Post'),
        ),
        migrations.AddField(
            model_name='genre',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='karaoke.Genre'),
        ),
    ]
