# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 09:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karaoke', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genre',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='karaoke.Genre'),
        ),
        migrations.CreateModel(
            name='Karaoke',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='karaoke.Post')),
                ('file', models.FileField(blank=True, null=True, upload_to='posts/songs')),
                ('composer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composed', to='loginapp.Artist')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karaoke.Genre')),
                ('poet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loginapp.Artist')),
            ],
            options={
                'ordering': ['created_date'],
            },
            bases=('karaoke.post',),
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='karaoke.Post')),
                ('text', models.CharField(default='', max_length=1500)),
                ('poet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loginapp.Artist')),
            ],
            bases=('karaoke.post',),
        ),
        migrations.AddField(
            model_name='karaoke',
            name='related_poem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karaoke.Poem'),
        ),
        migrations.AddField(
            model_name='karaoke',
            name='singer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='singed', to='loginapp.Artist'),
        ),
    ]
