# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, default='new-genre', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='karaoke',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='KaraokeFiles'),
        ),
        migrations.AlterField(
            model_name='karaoke',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karaoke.Genre'),
        ),
    ]
