# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 16:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediafiles', '0001_initial'),
        ('analytics', '0002_auto_20171011_2019'),
        ('karaoke', '0001_initial'),
        ('loginapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genre',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='karaoke.Genre'),
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='karaoke.Post')),
                ('text', models.CharField(default='', max_length=1500)),
                ('poet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loginapp.Artist')),
            ],
            bases=('karaoke.post',),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='karaoke.Post')),
                ('duration', models.FloatField(blank=True, null=True)),
                ('composer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composed', to='loginapp.Artist')),
                ('file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_song', to='mediafiles.MediaFile')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karaoke.Genre')),
                ('poet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_poems', to='loginapp.Artist')),
                ('related_poem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karaoke.Poem')),
                ('singer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='singed', to='loginapp.Artist')),
            ],
            bases=('karaoke.post',),
        ),
        migrations.AddField(
            model_name='post',
            name='cover_photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_cover', to='mediafiles.MediaFile'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(through='analytics.TagPost', to='analytics.Tag'),
        ),
    ]
