# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0002_auto_20170811_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['start_time']},
        ),
    ]
