# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0002_auto_20170905_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subclass_type',
            field=models.CharField(choices=[('karaoke', 'karaoke object'), ('poem', 'poem object')], default='karaoke', max_length=20),
        ),
    ]
