# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0001_initial'),
        ('loginapp', '0001_initial'),
        ('karaoke', '0002_auto_20171111_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karaoke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(blank=True, null=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loginapp.Artist')),
                ('file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_karaoke', to='mediafiles.MediaFile')),
                ('lyric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karaoke.Poem')),
            ],
        ),
        migrations.AddField(
            model_name='genre',
            name='cover_photo',
            field=models.FileField(blank=True, null=True, upload_to='genre_covers'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='subclass_type',
            field=models.CharField(choices=[('song', 'song object'), ('poem', 'poem object'), ('karaoke', 'Karaoke object')], default='song', max_length=20),
        ),
        migrations.AddField(
            model_name='karaoke',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='karaoke.Post'),
        ),
    ]
