# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0003_post_subclass_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='karaoke',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='subclass_type',
            field=models.CharField(choices=[('song', 'karaoke object'), ('poem', 'poem object')], default='song', max_length=20),
        ),
    ]
