# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0003_auto_20171116_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['id']},
        ),
    ]
