# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0004_auto_20170905_1052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Karaoke',
            new_name='Song',
        ),
        migrations.AlterField(
            model_name='post',
            name='subclass_type',
            field=models.CharField(choices=[('song', 'song object'), ('poem', 'poem object')], default='song', max_length=20),
        ),
    ]
