# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0004_auto_20170812_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaoke',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
    ]
