# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-19 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0004_auto_20171116_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='composer',
        ),
        migrations.RemoveField(
            model_name='song',
            name='poet',
        ),
        migrations.RemoveField(
            model_name='song',
            name='related_poem',
        ),
        migrations.RemoveField(
            model_name='song',
            name='singer',
        ),
        migrations.AddField(
            model_name='song',
            name='karaoke',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='karaoke.Karaoke'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='as_song', to='mediafiles.MediaFile'),
        ),
    ]
