# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 12:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0005_auto_20170812_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karaoke',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 13, 11, 59, 59, 44603, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
