# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 11:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_artist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('karaoke', '0006_auto_20170813_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaoke',
            name='composer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composed', to='loginapp.Artist'),
        ),
        migrations.AddField(
            model_name='karaoke',
            name='poem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poetried', to='loginapp.Artist'),
        ),
        migrations.AddField(
            model_name='karaoke',
            name='singer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='singed', to='loginapp.Artist'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
