# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0006_auto_20170910_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='desc',
            new_name='description',
        ),
    ]
