# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0007_auto_20170822_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='karaoke',
            options={'ordering': ['created_date']},
        ),
    ]
