# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0007_auto_20170910_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownership',
            old_name='type',
            new_name='ownership_type',
        ),
    ]
