# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0008_remove_post_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karaoke',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_karaoke', to='mediafiles.MediaFile'),
        ),
        migrations.AlterField(
            model_name='karaoke',
            name='full_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_full_karaoke', to='mediafiles.MediaFile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_cover', to='mediafiles.MediaFile'),
        ),
    ]
