# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_tag_tagpost'),
        ('karaoke', '0008_auto_20170911_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(through='analytics.TagPost', to='analytics.Tag'),
        ),
    ]
