# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0011_merge_20170827_1006'),
        ('karaoke', '0008_auto_20170830_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='new-poem', max_length=100)),
                ('poet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loginapp.Artist')),
            ],
        ),
        migrations.RenameField(
            model_name='karaoke',
            old_name='poem',
            new_name='poet',
        ),
        migrations.AlterField(
            model_name='line',
            name='karaoke',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karaoke.Karaoke'),
        ),
        migrations.AddField(
            model_name='line',
            name='poem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karaoke.Poem'),
        ),
    ]
