# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import karaoke.models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0009_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=karaoke.models.get_song_file_path),
        ),
    ]
