# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0009_auto_20170901_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaoke',
            name='poem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karaoke.Poem'),
        ),
    ]
