# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-26 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0009_auto_20180222_1922'),
        ('karaoke', '0009_auto_20180222_2144'),
    ]

    operations = [
    ]
