# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-04 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0010_merge_20180226_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='text'
        ),
        migrations.AddField(
            model_name='poem',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_poem', to='mediafiles.MediaFile'),
        ),
    ]
