# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-12 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0010_merge_20180226_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
