# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-12 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0011_post_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='popularity_rate',
            field=models.FloatField(default=0),
        ),
    ]
