# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-16 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0012_post_popularity_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
