# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-01 17:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import karaoke.models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0013_post_last_time_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaoke',
            name='mid',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='karaoke',
            name='mid_file',
            field=models.FileField(blank=True, null=True, upload_to=karaoke.models.get_mid_file_path),
        ),
    ]
