# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-21 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0014_auto_20180702_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_premium',
            field=models.BooleanField(default=True),
        ),
    ]
