# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-25 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0015_auto_20180821_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
