# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-06 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_banner_description'),
        ('karaoke', '0016_auto_20180825_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='new-feed', max_length=32)),
                ('code', models.CharField(blank=True, max_length=12, null=True)),
                ('from_date', models.DateTimeField(blank=True, null=True)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='karaoke.Genre')),
                ('tags', models.ManyToManyField(to='analytics.Tag')),
            ],
        ),
    ]
