# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-07 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0018_feed_order_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='tags',
            field=models.ManyToManyField(blank=True, to='analytics.Tag'),
        ),
    ]
