# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-27 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0021_auto_20181116_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='genre',
            name='index',
            field=models.SmallIntegerField(default=0),
        ),
    ]
