# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-05 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0023_post_legal'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
