# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-05 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0024_song_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
