# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-22 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0005_auto_20180622_1917'),
        ('karaoke', '0025_auto_20190305_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_thumbnail', to='mediafiles.MediaFile'),
        ),
    ]
