# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 11:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20170921_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfilehistory',
            name='requested_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_files_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
