# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20170923_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['time']},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['time']},
        ),
    ]
