# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_like_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='type',
        ),
    ]
