# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 19:17
from __future__ import unicode_literals

import analytics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20170929_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=analytics.models.get_path)),
                ('title', models.CharField(help_text='Persian text that will be shown ti user', max_length=100)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('clicked_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
