# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='content_type',
            field=models.CharField(choices=[('post', 'post object'), ('song', 'song object'), ('poem', 'poem object')], default='song', max_length=10),
        ),
    ]
