# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-11 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_banner_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='platform',
            field=models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], default='ios', max_length=8),
        ),
    ]
