# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_userfilehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfilehistory',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
