# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_banner_content_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='banner',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
