# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0004_auto_20170929_1709'),
        ('analytics', '0008_auto_20170930_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfilehistory',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download_history', to='karaoke.Post'),
        ),
    ]
