# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 15:32
from __future__ import unicode_literals

import analytics.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0004_auto_20170929_1709'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0009_userfilehistory_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_created=True)),
                ('type', models.CharField(choices=[(analytics.models.Like, 'Like Event'), ('follow', 'Follow Event')], default=analytics.models.Like, max_length=16)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karaoke.Post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_event', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
    ]
