# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
