# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 15:52
from __future__ import unicode_literals

import analytics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_auto_20171011_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[(analytics.models.Like, 'Like Event'), ('follow', 'Follow Event')], default='like', max_length=16),
        ),
    ]
