# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_auto_20171011_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('like', 'Like Event'), ('follow', 'Follow Event')], default='like', max_length=16),
        ),
    ]
