# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_auto_20171011_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-creation_date']},
        ),
    ]
