# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-20 20:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='بسته\u200cی جدید', max_length=64)),
                ('icon', models.FileField(blank=True, null=True, upload_to='default_icons')),
                ('serial_number', models.CharField(blank=True, db_index=True, help_text='این مقدار بایستی منحصر بفرد باشد، در صورت خالی گذاشتن مقدار دهی خواهد شد', max_length=16, null=True, unique=True)),
                ('days', models.IntegerField(blank=True, default=0)),
                ('weeks', models.IntegerField(blank=True, default=0)),
                ('months', models.IntegerField(blank=True, default=0)),
                ('years', models.IntegerField(blank=True, default=0)),
                ('total_days', models.IntegerField(blank=True, default=0, help_text='نیازی به پر کردن این مقدار نیست')),
                ('price', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('days', models.IntegerField(default=0)),
                ('applied', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
