# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-04 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_banktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymenttransaction',
            name='transaction_info',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
