# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-04 13:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0004_auto_20181116_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='BazzarTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('created', 'ساخته شده'), ('in_progress', 'به اپ ارسال شده'), ('returned', 'بازگشت از اپ'), ('success', 'اتمام'), ('verify_failed', 'خطا در تایید')], default='created', max_length=20)),
                ('serial_number', models.CharField(max_length=24)),
                ('ref_id', models.CharField(blank=True, max_length=48, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(blank=True, null=True)),
                ('package_applied', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='cointransaction',
            name='serial_number',
            field=models.CharField(default='nothing', max_length=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspackage',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, help_text='این مقدار بایستی منحصر بفرد باشد، در صورت خالی گذاشتن مقدار دهی خواهد شد', max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bazzartransaction',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.BusinessPackage'),
        ),
        migrations.AddField(
            model_name='bazzartransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cointransaction',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.BazzarTransaction'),
        ),
    ]
