# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-11 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_auto_20190104_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesspackage',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='businesspackage',
            name='index',
            field=models.SmallIntegerField(default=0),
        ),
    ]
