# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-16 10:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karaoke', '0021_auto_20181116_1355'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0004_auto_20181116_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PostProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('post', 'Post Property')], default='post', max_length=8)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('exp_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Inventory')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karaoke.Post')),
                ('tran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.CoinTransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='posts',
            field=models.ManyToManyField(through='inventory.PostProperty', to='karaoke.Post'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
