# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0005_auto_20171119_1358'),
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genres',
            field=models.ManyToManyField(blank=True, to='karaoke.Genre'),
        ),
    ]
