# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(db_index=True, max_length=128, primary_key=True, serialize=False),
        ),
    ]
