# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_artist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
