# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
