# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_user_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='public',
            new_name='is_public',
        ),
    ]
