# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_auto_20171204_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='code',
            field=models.CharField(db_index=True, max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='verification',
            unique_together=set([('code', 'user')]),
        ),
    ]
