# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-04 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_auto_20171225_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='build_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='last_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='one_signal_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
