# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_remove_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(blank=True, default=0, null=True),
        ),
    ]
