# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-02 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0007_artist_image_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='bundle',
            field=models.CharField(default='com.application.canto', max_length=32),
        ),
    ]
