# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0007_auto_20170817_0042'),
        ('loginapp', '0004_follow'),
    ]

    operations = [
    ]
