# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-04 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0008_device_bundle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='type',
            field=models.CharField(choices=[('sms', 'sms code'), ('email', 'email code'), ('upload', 'upload code')], default='sms', max_length=10),
        ),
    ]
