# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0009_auto_20170819_2103'),
        ('loginapp', '0009_auto_20170824_0809'),
    ]

    operations = [
    ]
