# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0010_merge_20170827_0929'),
        ('loginapp', '0010_merge_20170824_0909'),
    ]

    operations = [
    ]
