# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0011_merge_20170827_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
