# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-22 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0015_auto_20190106_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='market',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
